### ISSUE TITLE
Installation from source - cargo failed to load source for dependency `yew_form`

### ISSUE THREAD

**Issue by EmTeeAge** [nitnelave/lldap#306]
Hello,

I have tried installing lldap by building from source and ran into an issue when running the following command:

`cargo build --release -p lldap -p migration-tool`

The error is following:
```
    Updating git repository `https://github.com/sassman/yew_form/`
error: failed to load source for dependency `yew_form`

Caused by:
  Unable to update https://github.com/sassman/yew_form/?rev=67050812695b7a8a90b81b0637e347fc6629daed#67050812

Caused by:
  failed to fetch into: /home/myuser/.cargo/git/db/yew_form-bed4afe5ae5d502f

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via git's `credential.helper` support, but failed

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to acquire username/password from local configuration
```

First I though it had something with my local configuration of cargo or mistake on my side, but after examining Cargo.toml, it looks like yew_form is a dependency of lldap.
Unfortunately, it looks like the repo at https://github.com/sassman/yew_form is gone.

Based on the information in Cargo.toml, it should be removed "when there's a new release", however I have no idea which release and whether it is still supposed to be there.

```
[workspace]
members = [
  "server",
  "auth",
  "app",
  "migration-tool"
]

default-members = ["server"]

# TODO: remove when there's a new release.
[patch.crates-io.yew_form]
git = 'https://github.com/sassman/yew_form/'
rev = '67050812695b7a8a90b81b0637e347fc6629daed'

[patch.crates-io.yew_form_derive]
git = 'https://github.com/sassman/yew_form/'
rev = '67050812695b7a8a90b81b0637e347fc6629daed'
```

After commenting out the references to yew_form, I managed to get further but ended up on a different error - this time regarding yew_form verions.

```
    Updating crates.io index
error: failed to select a version for the requirement `yew_form = "^0.1.8"`
candidate versions found which didn't match: 0.1.7, 0.1.5, 0.1.4, ...
location searched: crates.io index
required by package `lldap_app v0.4.0 (/var/www/lldap/app)`
```

Could you provide me with some tips or help how to get rid of this?

Thank you very much

**Comment by EmTeeAge** [comment]
According to crates.io, there's no package named yew_form in version 0.1.8, only 0.1.7.

I managed to get around the version error by editing Cargo.toml in the ./app folder and replacing yew_form = "0.1.8" with yew_form = "0.1.7"

After this modification, the build finished and I was able to move on.

**Comment by EmTeeAge** [comment]
Well, in the end the installation failed eventually in the last step when running build.sh

```
./build.sh
[INFO]: Checking for the Wasm target...
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
 16.9 MiB /  16.9 MiB (100 %)   9.8 MiB/s in  1s ETA:  0s
[INFO]: Compiling to Wasm...
   Compiling syn v1.0.98
   Compiling serde v1.0.137
   Compiling serde_json v1.0.82
   Compiling lazy_static v1.4.0
   Compiling log v0.4.17
   Compiling wasm-bindgen-shared v0.2.81
   Compiling bumpalo v3.10.0
   Compiling wasm-bindgen v0.2.81
   Compiling cfg-if v1.0.0
   Compiling ryu v1.0.10
   Compiling itoa v1.0.2
   Compiling futures-core v0.3.21
   Compiling futures-channel v0.3.21
   Compiling futures-util v0.3.21
   Compiling lexical-core v0.7.6
   Compiling boolinator v2.4.0
   Compiling proc-macro-nested v0.1.7
   Compiling subtle v2.4.1
   Compiling slab v0.4.6
   Compiling cc v1.0.73
   Compiling futures-sink v0.3.21
   Compiling arrayvec v0.5.2
   Compiling tinyvec_macros v0.1.0
   Compiling yew v0.17.4
   Compiling bytes v1.1.0
   Compiling fnv v1.0.7
   Compiling futures-io v0.3.21
   Compiling hashbrown v0.9.1
   Compiling matches v0.1.9
   Compiling pin-utils v0.1.0
   Compiling if_chain v1.0.2
   Compiling percent-encoding v2.1.0
   Compiling cfg-match v0.2.1
   Compiling unicode-bidi v0.3.8
   Compiling unicode-ident v1.0.1
   Compiling static_assertions v1.1.0
   Compiling anymap v0.12.1
   Compiling pin-project-lite v0.2.9
   Compiling byteorder v1.4.3
   Compiling either v1.7.0
   Compiling regex-syntax v0.6.26
   Compiling ppv-lite86 v0.2.16
   Compiling yew v0.18.0
   Compiling base64 v0.13.0
   Compiling bitflags v1.3.2
   Compiling cfg-if v0.1.10
   Compiling once_cell v1.12.0
   Compiling opaque-debug v0.3.0
   Compiling arrayref v0.3.6
   Compiling constant_time_eq v0.1.5
   Compiling proc-macro2 v1.0.40
   Compiling quote v1.0.20
   Compiling memchr v2.5.0
   Compiling nom v5.1.2
   Compiling indexmap v1.6.2
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling typenum v1.15.0
   Compiling futures-task v0.3.21
   Compiling libc v0.2.126
   Compiling anyhow v1.0.58
   Compiling backtrace v0.3.65
   Compiling tinyvec v1.6.0
   Compiling getrandom v0.1.16
   Compiling http v0.2.8
   Compiling form_urlencoded v1.0.1
   Compiling crossbeam-utils v0.8.10
   Compiling blake2b_simd v0.5.11
   Compiling generic-array v0.14.5
   Compiling unicode-normalization v0.1.20
   Compiling combine v3.8.1
   Compiling aho-corasick v0.7.18
   Compiling time v0.1.44
   Compiling idna v0.2.3
   Compiling rand_core v0.5.1
   Compiling rust-argon2 v0.8.3
   Compiling regex v1.5.6
   Compiling yew-router-route-parser v0.15.0
   Compiling url v2.2.2
   Compiling wasm-bindgen-backend v0.2.81
   Compiling synstructure v0.12.6
   Compiling validator_types v0.14.0
   Compiling serde_derive v1.0.137
   Compiling thiserror-impl v1.0.31
   Compiling futures-macro v0.3.21
   Compiling yew-macro v0.17.0
   Compiling yew-macro v0.18.0
   Compiling displaydoc v0.1.7
   Compiling proc-macro-error v1.0.4
   Compiling yew-router-macro v0.15.0
   Compiling wasm-bindgen-macro-support v0.2.81
   Compiling failure_derive v0.1.8
   Compiling zeroize_derive v1.3.2
   Compiling thiserror v1.0.31
   Compiling validator_derive v0.14.0
   Compiling wasm-bindgen-macro v0.2.81
   Compiling failure v0.1.8
   Compiling zeroize v1.1.1
   Compiling bincode v1.3.3
   Compiling graphql-introspection-query v0.2.0
   Compiling futures-executor v0.3.21
   Compiling graphql-parser v0.2.3
   Compiling validator v0.10.1
   Compiling validator v0.14.0
   Compiling digest v0.9.0
   Compiling crypto-mac v0.11.1
   Compiling block-buffer v0.9.0
   Compiling generic-bytes v0.1.0
   Compiling crypto-mac v0.10.1
   Compiling futures v0.3.21
   Compiling graphql_client_codegen v0.10.0
   Compiling js-sys v0.3.58
   Compiling console_error_panic_hook v0.1.7
   Compiling curve25519-dalek v3.2.1
   Compiling hmac v0.11.0
   Compiling sha2 v0.9.9
   Compiling hmac v0.10.1
   Compiling validator_derive v0.10.1
   Compiling graphql_query_derive v0.10.0
   Compiling web-sys v0.3.58
   Compiling gloo-timers v0.2.4
   Compiling wasm-bindgen-futures v0.4.31
   Compiling getrandom v0.2.7
   Compiling chrono v0.4.19
   Compiling hkdf v0.11.0
   Compiling jwt v0.13.0
   Compiling graphql_client v0.10.0
   Compiling gloo-events v0.1.2
   Compiling gloo-console-timer v0.1.0
   Compiling rand_core v0.6.3
   Compiling gloo-file v0.1.0
   Compiling rand_chacha v0.3.1
   Compiling gloo v0.2.1
   Compiling rand v0.8.5
   Compiling opaque-ke v0.6.1
   Compiling yew-router v0.15.0
   Compiling yewtil v0.4.0
   Compiling yew_form v0.1.7
   Compiling lldap_auth v0.3.0-alpha.1 (/var/www/lldap/auth)
   Compiling yew_form_derive v0.1.7
error[E0432]: unresolved import `syn::export`
 --> /home/marek-admin/.cargo/registry/src/github.com-1ecc6299db9ec823/yew_form_derive-0.1.7/src/lib.rs:6:10
  |
6 | use syn::export::{ToTokens, TokenStream};
  |          ^^^^^^ could not find `export` in `syn`

error[E0599]: no method named `to_tokens` found for reference `&syn::Path` in the current scope
  --> /home/marek-admin/.cargo/registry/src/github.com-1ecc6299db9ec823/yew_form_derive-0.1.7/src/lib.rs:32:22
   |
32 |                 path.to_tokens(&mut tokens);
   |                      ^^^^^^^^^ method not found in `&syn::Path`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
2  | use crate::quote::ToTokens;
   |

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `yew_form_derive` due to 2 previous errors
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"

./main.js → ./pkg/bundle.js...
[!] Error: Could not resolve './pkg/lldap_app.js' from main.js
Error: Could not resolve './pkg/lldap_app.js' from main.js
    at error (/var/www/lldap/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/var/www/lldap/node_modules/rollup/dist/shared/rollup.js:22287:24)
    at /var/www/lldap/node_modules/rollup/dist/shared/rollup.js:22250:26

```

**Comment by nitnelave** [comment]
Do you have the latest code? I fixed that dependency a while ago, the repo
is now jfbilodeau/yew_form

**Comment by EmTeeAge** [comment]
Hi,

I used the latest source code from Releases, which is version v0.4.0. I haven't tried with the current code in the repo yet, I guess that could be the issue. Thanks.

**Comment by EmTeeAge** [comment]
When building from the latest commit, I was able to compile the server, but know I'm unable to get the webUI up and running. I've tried playing around with different permissions, users and file paths, but I always seem to end up with this error.

The webUI on port 17170 loads with `No such file or directory (os error 2)`

```
/var/www/lldap/target/release$ cargo run -- run

    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `/var/www/lldap/target/debug/lldap run`
Loading configuration from lldap_config.toml
WARNING: Default JWT secret used! This is highly unsafe and can allow attackers to log in as admin.
WARNING: Unsecure default admin password is used.
2022-09-29T20:12:30.199336103+00:00 INFO     set_up_server [ 10.0ms | 100.00% ]
2022-09-29T20:12:30.199469376+00:00 INFO     ┝━ ｉ [info]: Starting LLDAP version 0.4.0
2022-09-29T20:12:30.216068789+00:00 INFO     ┝━ ｉ [info]: Starting the LDAP server on port 3890
2022-09-29T20:12:30.220262052+00:00 INFO     ┕━ ｉ [info]: Starting the API/web server on port 17170
2022-09-29T20:12:30.221174138+00:00 INFO     ｉ [info]: Starting 1 workers | log.target: "actix_server::builder" | log.module_path: "actix_server::builder" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.5/src/builder.rs" | log.line: 281
2022-09-29T20:12:30.221865036+00:00 INFO     ｉ [info]: Starting "ldap" service on 0.0.0.0:3890 | log.target: "actix_server::builder" | log.module_path: "actix_server::builder" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.5/src/builder.rs" | log.line: 296
2022-09-29T20:12:30.221936294+00:00 INFO     ｉ [info]: Starting "http" service on 0.0.0.0:17170 | log.target: "actix_server::builder" | log.module_path: "actix_server::builder" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.5/src/builder.rs" | log.line: 296
2022-09-29T20:12:30.222264651+00:00 INFO     ｉ [info]: DB Cleanup Cron started
2022-09-29T20:12:30.223543069+00:00 ERROR    🚨 [error]: Specified path is not a directory: "./app/pkg" | log.target: "actix_files::files" | log.module_path: "actix_files::files" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-files-0.6.0-beta.6/src/files.rs" | log.line: 103
2022-09-29T20:12:30.223775583+00:00 ERROR    🚨 [error]: Specified path is not a directory: "./app/static" | log.target: "actix_files::files" | log.module_path: "actix_files::files" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-files-0.6.0-beta.6/src/files.rs" | log.line: 103
2022-09-29T20:12:30.223931646+00:00 ERROR    🚨 [error]: Specified path is not a directory: "./app/static/fonts" | log.target: "actix_files::files" | log.module_path: "actix_files::files" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-files-0.6.0-beta.6/src/files.rs" | log.line: 103
2022-09-29T20:12:32.431801927+00:00 INFO     HTTP request [ 249µs | 100.00% ]
2022-09-29T20:12:32.431866684+00:00 INFO     ┝━ ｉ [info]:  | uri: /ldap
2022-09-29T20:12:32.432182300+00:00 ERROR    ┝━ 🚨 [error]:  | error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
2022-09-29T20:12:32.432208830+00:00 WARN     ┕━ 🚧 [warn]: Error encountered while processing the incoming HTTP request: Os { code: 2, kind: NotFound, message: "No such file or directory" }
2022-09-29T20:12:34.087466733+00:00 INFO     HTTP request [ 181µs | 100.00% ]
2022-09-29T20:12:34.087512066+00:00 INFO     ┝━ ｉ [info]:  | uri: /
2022-09-29T20:12:34.087679963+00:00 ERROR    ┝━ 🚨 [error]:  | error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
2022-09-29T20:12:34.087703474+00:00 WARN     ┕━ 🚧 [warn]: Error encountered while processing the incoming HTTP request: Os { code: 2, kind: NotFound, message: "No such file or directory" }
^C2022-09-29T20:12:36.197295361+00:00 INFO     ｉ [info]: SIGINT received, exiting | log.target: "actix_server::builder" | log.module_path: "actix_server::builder" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.5/src/builder.rs" | log.line: 344
2022-09-29T20:12:36.197637319+00:00 INFO     ｉ [info]: DB Cleanup stopped
2022-09-29T20:12:36.198008335+00:00 INFO     ｉ [info]: End.
2022-09-29T20:12:36.198204506+00:00 INFO     ｉ [info]: Paused accepting connections on 0.0.0.0:3890 | log.target: "actix_server::accept" | log.module_path: "actix_server::accept" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.5/src/accept.rs" | log.line: 347
2022-09-29T20:12:36.198292555+00:00 INFO     ｉ [info]: Paused accepting connections on 0.0.0.0:17170 | log.target: "actix_server::accept" | log.module_path: "actix_server::accept" | log.file: "/home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.5/src/accept.rs" | log.line: 347
```

**Comment by nitnelave** [comment]
Repeating what was said on Discord for posterity: 
LLDAP needs access to the frontend files created by running ./app/build.sh, the app/pkg directory, index.html, and static files. They need to be next to where you run the binary, in the app/ subdirectory from your working directory.
In your case, it sounds like you cloned the repository in/var/www/lldap, so calling cargo run from there should work (after generating the frontend build files)

**Comment by EmTeeAge** [comment]
Thank you for the help!

It turned out to be issue with paths. I got a bit confused and was trying commands in the wrong paths.

I ended up with the following systemd configuration file, which now works correctly.

```
[Unit]
Description=Nitnelave LLDAP
Documentation=https://github.com/nitnelave/lldap

# Only sqlite
After=network.target

[Service]
# The user/group LLDAP is run under. The working directory (see below) should allow write and read access to this user/group.
User=www-data
Group=www-data

# The location of the compiled binary
ExecStart=/var/www/lldap/target/release/lldap run

# Only allow writes to the following directory and set it to the working directory (user and password data are stored here).
WorkingDirectory=/var/www/lldap/
ReadWriteDirectories=/var/www/lldap/

[Install]
WantedBy=multi-user.target
```

What also got me in the example systemd file (https://github.com/nitnelave/lldap/blob/main/example_configs/lldap.service) was this bit:

```
# The location of the compiled binary
ExecStart=/opt/nitnelave/lldap \
  run
```

Why is there the \ and run is on the second line? In my case it works fine like this:

```
# The location of the compiled binary
ExecStart=/var/www/lldap/target/release/lldap run
```

Thank you.
